name: Build DirtyCow ARM32

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM32 soft-float cross compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabi libc6-dev-armel-cross

      - name: Compile dirtycow for ARMv7
        run: |
          arm-linux-gnueabi-gcc dirtycow.c -o dirtycow_arm32 \
            -pthread -pie -fPIE -static -march=armv7-a

      - name: Upload compiled exp
        uses: actions/upload-artifact@v4
        with:
          name: dirtycow-arm32-exp
          path: dirtycow_arm32
